name: Feature Request
description: Suggest an idea or enhancement for jellybeans.nvim
title: "[Feature]: "
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature or enhancement for jellybeans.nvim!
        Please complete the following information to help us understand your request.

  - type: checkboxes
    id: pre-checks
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting your feature request
      options:
        - label: I have searched existing issues to avoid creating duplicates
          required: true
        - label: I have checked the documentation to confirm this feature doesn't already exist
          required: true
        - label: This feature is related to jellybeans.nvim and not another plugin
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is
      placeholder: I'm always frustrated when [...]
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen
      placeholder: I would like jellybeans.nvim to support [...]
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered
      placeholder: I've tried using [...] as a workaround, but it doesn't fully solve the problem because [...]
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or mockups
      description: If applicable, add screenshots or mockups to help explain your feature request
      placeholder: Drag and drop images here or describe the visual appearance you're looking for
    validations:
      required: false

  - type: textarea
    id: config
    attributes:
      label: Configuration example
      description: If possible, provide an example of how you envision configuring this feature
      placeholder: |
        ```lua
        -- Example configuration for the requested feature
        require('jellybeans').setup({
          -- Your proposed configuration options
          new_feature = {
            enabled = true,
            option1 = "value1",
            option2 = "#ff5500"
          }
        })
        ```
      render: lua
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the feature request here
      placeholder: Any additional information that might be helpful...
    validations:
      required: false