[manager]
cwd = { fg = "#2d2c2a", italic = true }

# Hovered
hovered = { bg = "#ebe7df" }
preview_hovered = { bg = "#ebe7df" }

# Find
find_keyword = { fg = "#f7f3eb", bg = "#a07542", bold = true }
find_position = { fg = "#3a6f8c", bg = "#3c5884", bold = true }

# Marker
marker_copied = { fg = "#4d7134", bg = "#4d7134" }
marker_cut = { fg = "#913a34", bg = "#913a34" }
marker_marked = { fg = "#655683", bg = "#655683" }
marker_selected = { fg = "#f7f3eb", bg = "#a07542" }

# Tab
tab_active = { fg = "#2d2c2a", bg = "#ebe7df" }
tab_inactive = { fg = "#5f5f5d", bg = "#f7f3eb" }
tab_width = 1

# Count
count_copied = { fg = "#f7f3eb", bg = "#35635d" }
count_cut = { fg = "#f7f3eb", bg = "#913a34" }
count_selected = { fg = "#f7f3eb", bg = "#3c5884" }

# Border
border_symbol = "│"
border_style = { fg = "#ebe7df" }

[status]
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

progress_label = { fg = "#2d2c2a", bold = true }
progress_normal = { fg = "#f7f3eb" }
progress_error = { fg = "#913a34" }

# Permissions
permissions_t = { fg = "#445987" }
permissions_r = { fg = "#a07542" }
permissions_w = { fg = "#8c594a" }
permissions_x = { fg = "#6d7f59" }
permissions_s = { fg = "#d0cdc6" }

[mode]
normal_main = { fg = "#f7f3eb", bg = "#3c5971", bold = true }
normal_alt = { fg = "#f7f3eb", bg = "#5f5f5d" }

select_main = { fg = "#f7f3eb", bg = "#655683", bold = true }
select_alt = { fg = "#f7f3eb", bg = "#5f5f5d" }

unset_main = { fg = "#f7f3eb", bg = "#542258", bold = true }
unset_alt = { fg = "#f7f3eb", bg = "#5f5f5d" }

[select]
border = { fg = "#3a6f8c" }
active = { fg = "#2d2c2a", bg = "#3c5884" }
inactive = { fg = "#2d2c2a" }

[input]
border = { fg = "#3a6f8c" }
title = {}
value = { fg = "#655683" }
selected = { bg = "#3c5884" }

[completion]
border = { fg = "#3a6f8c" }
active = { fg = "#2d2c2a", bg = "#3c5884" }
inactive = { fg = "#2d2c2a" }

[tasks]
border = { fg = "#3a6f8c" }
title = {}
hovered = { fg = "#2d2c2a", bg = "#3c5884" }

[which]
cols = 3
mask = { bg = "#f7f3eb" }
cand = { fg = "#3c5971" }
rest = { fg = "#445987" }
desc = { fg = "#655683" }
separator = "  "
separator_style = { fg = "#787775" }

[notify]
title_info = { fg = "#3a6f8c" }
title_warn = { fg = "#a07542" }
title_error = { fg = "#913a34" }

[help]
on = { fg = "#6d7f59" }
run = { fg = "#655683" }
hovered = { bg = "#3c5884" }
footer = { fg = "#2d2c2a", bg = "#f7f3eb" }

[filetype]
rules = [
  # Media
  { mime = "{audio,video,image}/*", fg = "#655683" },

  # Archives
  { mime = "application/*zip", fg = "#913a34" },
  { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#913a34" },

  # Documents
  { mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#3c5971" },

  # Special files
  { name = "*", is = "link", fg = "#8c594a" },
  { name = "*/", is = "link", fg = "#8c594a" },
  { name = "*", is = "orphan", bg = "#913a34" },
  { name = "*", is = "exec", fg = "#6d7f59" },

  # Fallback
  { name = "*/", fg = "#445987" },
]
