[manager]
cwd = { fg = "#252525", italic = true }

# Hovered
hovered = { bg = "#e8d5c0" }
preview_hovered = { bg = "#e8d5c0" }

# Find
find_keyword = { fg = "#f5e6d3", bg = "#b87520", bold = true }
find_position = { fg = "#1670af", bg = "#2952a3", bold = true }

# Marker
marker_copied = { fg = "#386014", bg = "#386014" }
marker_cut = { fg = "#a02020", bg = "#a02020" }
marker_marked = { fg = "#6a4abd", bg = "#6a4abd" }
marker_selected = { fg = "#f5e6d3", bg = "#b87520" }

# Tab
tab_active = { fg = "#252525", bg = "#e8d5c0" }
tab_inactive = { fg = "#606060", bg = "#f5e6d3" }
tab_width = 1

# Count
count_copied = { fg = "#f5e6d3", bg = "#2D7067" }
count_cut = { fg = "#f5e6d3", bg = "#a02020" }
count_selected = { fg = "#f5e6d3", bg = "#2952a3" }

# Border
border_symbol = "│"
border_style = { fg = "#e8d5c0" }

[status]
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

progress_label = { fg = "#252525", bold = true }
progress_normal = { fg = "#f5e6d3" }
progress_error = { fg = "#a02020" }

# Permissions
permissions_t = { fg = "#2952a3" }
permissions_r = { fg = "#b87520" }
permissions_w = { fg = "#954d3b" }
permissions_x = { fg = "#658349" }
permissions_s = { fg = "#d0ccd1" }

[mode]
normal_main = { fg = "#f5e6d3", bg = "#2B5B77", bold = true }
normal_alt = { fg = "#f5e6d3", bg = "#606060" }

select_main = { fg = "#f5e6d3", bg = "#6a4abd", bold = true }
select_alt = { fg = "#f5e6d3", bg = "#606060" }

unset_main = { fg = "#f5e6d3", bg = "#5a0069", bold = true }
unset_alt = { fg = "#f5e6d3", bg = "#606060" }

[select]
border = { fg = "#1670af" }
active = { fg = "#252525", bg = "#2952a3" }
inactive = { fg = "#252525" }

[input]
border = { fg = "#1670af" }
title = {}
value = { fg = "#6a4abd" }
selected = { bg = "#2952a3" }

[completion]
border = { fg = "#1670af" }
active = { fg = "#252525", bg = "#2952a3" }
inactive = { fg = "#252525" }

[tasks]
border = { fg = "#1670af" }
title = {}
hovered = { fg = "#252525", bg = "#2952a3" }

[which]
cols = 3
mask = { bg = "#f5e6d3" }
cand = { fg = "#2B5B77" }
rest = { fg = "#2952a3" }
desc = { fg = "#6a4abd" }
separator = "  "
separator_style = { fg = "#787878" }

[notify]
title_info = { fg = "#1670af" }
title_warn = { fg = "#b87520" }
title_error = { fg = "#a02020" }

[help]
on = { fg = "#658349" }
run = { fg = "#6a4abd" }
hovered = { bg = "#2952a3" }
footer = { fg = "#252525", bg = "#f5e6d3" }

[filetype]
rules = [
  # Media
  { mime = "{audio,video,image}/*", fg = "#6a4abd" },

  # Archives
  { mime = "application/*zip", fg = "#a02020" },
  { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#a02020" },

  # Documents
  { mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#2B5B77" },

  # Special files
  { name = "*", is = "link", fg = "#954d3b" },
  { name = "*/", is = "link", fg = "#954d3b" },
  { name = "*", is = "orphan", bg = "#a02020" },
  { name = "*", is = "exec", fg = "#658349" },

  # Fallback
  { name = "*/", fg = "#2952a3" },
]
